modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="runeroller"
version="${mod_version}"
displayName="Runeroller"
authors="${mod_authors}"
description='''${mod_description}'''

# -------------------------
# NeoForge dependency
# -------------------------
[[dependencies.runeroller]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

# -------------------------
# Minecraft dependency
# -------------------------
[[dependencies.runeroller]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

# -------------------------
# Runeroller Coins dependency (IMPORTANT)
# -------------------------
[[dependencies.runeroller]]
modId="runeroller_coins"
type="required"
versionRange="[1,)"
ordering="AFTER"
side="BOTH"
